import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from '@/components/theme-provider'
import { Navbar } from "@/components/navbar";


export const metadata: Metadata = {
  title: "ChatQL",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen bg-background text-foreground flex flex-col">
            
            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
