import { ThemeProvider } from '@/components/theme-provider'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "AskDB",
  description: "Generated by create next app",
};


export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen bg-background text-foreground flex flex-col">
            
            {children}
          </div>
        </ThemeProvider>
  );
}
