import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from '@/components/theme-provider'
import { Navbar } from "@/components/navbar";
import AdminNavbar from "@/components/admin-navbar";


export const metadata: Metadata = {
  title: "Text to SQL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen bg-background text-foreground flex flex-col">
            <AdminNavbar/>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
