import { ThemeProvider } from '@/components/theme-provider'
import { Navbar } from '@/components/navbar';
import { ClerkProvider } from "@clerk/nextjs"
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "AskDB: Admin",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen bg-background text-foreground flex flex-col">
            <Navbar/>
            {children}
          </div>
        </ThemeProvider>
    </ClerkProvider>
  );
}
